In [ ]:
import pandas as pd
import numpy
import nltk

In [ ]:
dataset = pd.read_csv('Resume_data.csv')
dataset.columns

Index(['file_name', 'name', 'email', 'phone_no', 'companies_worked', 'skills',
       'college', 'experience', 'designition'],
      dtype='object')

In [ ]:
dataset

file_name  ...                                        designition
0                              Mani_Hadoop  ...  ['hadoop developer', 'zookeeper', 'research sc...
1        Sougandh_Java Fullstack Developer  ...  ['full stack developer', 'locator', 'devops', ...
2                          Jagan S Iyer PM  ...  ['senior project manager', 'project manager', ...
3    Balaji Gopalakrishnan Project Manager  ...  ['it professional', 'technical project manager...
4                                     Dave  ...  ['java developer', 'plsql developer', 'oracle ...
..                                     ...  ...                                                ...
222                            komal patel  ...  ['full stack java developer', 'java developer'...
223                             kalyan das  ...  ['full stack java developer', 'java developer'...
224                             SAURABH_PM  ...  ['it project manager', 'project manager', 'qua...
225                              Sai kumar  ...  ['test director', 'director', 'enterprise mana...
226                               Sarath M  ...  ['full stack developer', 'business objects', '...

[227 rows x 9 columns]

In [ ]:
columns = dataset.columns

Steps
- All dataset in lower case - Dataset
- Rank all companies names from open source
- College Ranking from open source
- Skills Ranking | Companies required Skills
- Designition Ranking
- Experience Ranking




In [ ]:
len(dataset[columns[-2]])
dataset['experience'].isna().sum()

41

In [ ]:
s = pd.Series(dataset['experience'])
s.describe()

count     186.000000
mean      180.279570
std       635.325469
min     -2016.000000
25%         5.000000
50%         8.000000
75%        13.000000
max      2020.000000
Name: experience, dtype: float64

Remove na experience

In [ ]:
dataframe = dataset[dataset['experience'].isna() == False]

In [ ]:
dataframe

file_name  ...                                        designition
0                              Mani_Hadoop  ...  ['hadoop developer', 'zookeeper', 'research sc...
1        Sougandh_Java Fullstack Developer  ...  ['full stack developer', 'locator', 'devops', ...
2                          Jagan S Iyer PM  ...  ['senior project manager', 'project manager', ...
3    Balaji Gopalakrishnan Project Manager  ...  ['it professional', 'technical project manager...
4                                     Dave  ...  ['java developer', 'plsql developer', 'oracle ...
..                                     ...  ...                                                ...
222                            komal patel  ...  ['full stack java developer', 'java developer'...
223                             kalyan das  ...  ['full stack java developer', 'java developer'...
224                             SAURABH_PM  ...  ['it project manager', 'project manager', 'qua...
225                              Sai kumar  ...  ['test director', 'director', 'enterprise mana...
226                               Sarath M  ...  ['full stack developer', 'business objects', '...

[186 rows x 9 columns]

Remove outliers from experience

In [ ]:
dataframe['experience']

0         5.0
1        12.0
2        21.0
3        16.0
4      2014.0
        ...  
222    2008.0
223       5.0
224       5.0
225      14.0
226       8.0
Name: experience, Length: 186, dtype: float64

In [ ]:
from scipy import stats

z_scores = stats.zscore(dataframe['experience'])
print(z_scores)
z_score_abs = numpy.abs(z_scores)
filtered_entries = (z_score_abs < 2)
print(filtered_entries)
filtered_dataframe = dataframe[filtered_entries == True]
# Remove negative values
filtered_dataframe = filtered_dataframe[filtered_dataframe['experience'] >= 0]
# filtered_dataframe = [dataframe.iloc[i]['experience'] if exp else 0 for i, exp in enumerate(filtered_entries)]

[-0.27663405 -0.26558634 -0.25138214 -0.25927336  2.89405957 -0.27189932
 -0.27347756 -0.28294703 -0.27505581 -0.27663405 -0.27032108 -0.27663405
 -0.27347756 -0.27347756 -0.27189932 -0.25611687 -0.27189932  2.88143361
 -0.2782123  -0.27347756 -0.26716459  2.8845901  -0.27189932 -0.28136879
 -0.2782123  -0.2640081  -0.26558634 -0.28136879 -0.25296038 -0.25296038
 -0.2782123  -0.27505581 -0.27663405 -0.26716459 -0.26874283 -0.26874283
 -0.26558634 -0.27032108 -0.27663405 -0.26716459 -0.26242985 -0.26242985
 -0.27032108 -0.26716459 -0.27189932 -0.26558634  2.87827712 -0.27663405
 -0.25138214 -0.2782123  -0.26242985 -0.26085161 -0.28136879 -0.27979054
  2.89405957 -0.26716459 -3.45364066 -0.27663405 -0.27189932 -0.25453863
 -0.27505581 -0.2640081  -0.2782123  -0.27505581 -0.27347756 -0.27663405
 -0.27505581 -0.24980389 -0.28294703 -0.27663405 -0.2782123  -0.26242985
 -0.29715124 -0.25769512 -0.2640081  -0.25296038 -0.27505581 -0.26874283
 -0.2782123  -0.26716459  2.87985537 -0.27189932 -0

In [ ]:
filtered_dataframe = filtered_dataframe.reset_index()
filtered_dataframe = filtered_dataframe.sort_values('experience', ascending=False)
filtered_dataframe

index  ...                                        designition
61      79  ...  ['project manager', 'business development', 'i...
44      55  ...  ['project manager', 'oracle database administr...
2        2  ...  ['senior project manager', 'project manager', ...
68      90  ...  ['it project manager', 'project manager', 'ora...
26      34  ...  ['java developer', 'java application developer...
..     ...  ...                                                ...
87     116  ...  ['change management', 'business analyst', 'scr...
133    186  ...  ['deployment manager', 'sql server developer',...
62      80  ...  ['java developer', 'quality assurance', 'enter...
6        8  ...  ['senior project manager', 'project manager', ...
152    214  ...  ['sql developer', 'technology lead', 'full sta...

[163 rows x 10 columns]

Designition
- Count
- Ranking words

In [ ]:
filtered_dataframe.iloc[0]['designition'][2:-2].replace("'","").split(", ")

['project manager',
 'business development',
 'it manager',
 'it analyst',
 'change management',
 'quality assurance',
 'team lead',
 'team member',
 'certified scrum master',
 'scrum master']

In [ ]:
designition = [x for i in range(len(filtered_dataframe)) for x in filtered_dataframe.iloc[i]['designition'][2:-2].replace("'","").split(", ")]

In [ ]:
designition[100]

'quality control'

In [ ]:
designition_distinct = []
[designition_distinct.append(x) for x in designition if x not in designition_distinct]
len(designition_distinct)

369

In [ ]:
designition_rating = []
for desig in designition_distinct:
  print(desig)
  designition_rating.append(input())

In [ ]:
desig_rating = {}
for i in range(len(designition_distinct)):
  desig_rating[designition_distinct[i]] = designition_rating[i]

Reading designition rating

In [ ]:
import pickle
f = open('desig_rating.pkl','rb')
desig_rating = pickle.load(f)
desig_rating

Rate accordingly

In [ ]:
dataframe = filtered_dataframe.reset_index()

In [ ]:
rating_value = []
designition_count = []
for i in range(len(dataframe)):
  designition = [x for x in filtered_dataframe.iloc[i]['designition'][2:-2].replace("'","").split(", ")]
  value=0
  count=0
  for desig in designition:
    if desig in desig_rating.keys():
      value+=int(desig_rating[desig])
      count+=1
  rating_value.append(value)
  designition_count.append(count)

In [ ]:
dataframe['designition_rating']=rating_value
dataframe['designition_count']=designition_count

In [ ]:
dataframe

level_0  index  ... designition_rating designition_count
0         61     79  ...                 35                10
1         44     55  ...                 52                14
2          2      2  ...                 44                10
3         68     90  ...                 49                14
4         26     34  ...                 34                11
..       ...    ...  ...                ...               ...
158       87    116  ...                 44                12
159      133    186  ...                 23                 7
160       62     80  ...                 17                 6
161        6      8  ...                 73                23
162      152    214  ...                 21                 8

[163 rows x 13 columns]

In [ ]:
skills = [x for i in range(len(dataframe)) for x in dataframe.iloc[i]['skills'][2:-2].replace("'","").split(", ") if len(x) < 20]

In [ ]:
skills = [skill.strip() for skill in skills]

In [ ]:
skills

In [ ]:
selected_skills = []
[selected_skills.append(skill) for skill in skills if skill not in selected_skills]
len(selected_skills)

4281

Count of selected skills in skillset

In [ ]:
skill_count = []
for i in range(len(dataframe)):
  skills = [x.strip() for x in dataframe.iloc[i]['skills'][2:-2].replace("'","").split(", ")]
  count=0
  for skill in skills:
    if skill in selected_skills:
      count+=1
  skill_count.append(count)

In [ ]:
dataframe['skill_count']=skill_count

In [ ]:
dataframe

level_0  index  ... designition_count skill_count
0         61     79  ...                10         128
1         44     55  ...                14         183
2          2      2  ...                10         117
3         68     90  ...                14         182
4         26     34  ...                11         108
..       ...    ...  ...               ...         ...
158       87    116  ...                12         241
159      133    186  ...                 7         196
160       62     80  ...                 6          48
161        6      8  ...                23          15
162      152    214  ...                 8         105

[163 rows x 14 columns]

In [ ]:
dataframe['college'].isna().sum()

105

In [ ]:
dataframe['companies_worked'].isna().sum()

35

In [ ]:
dataframe['name'].isna().sum()

25

In [ ]:
dataframe['phone_no'].isna().sum()

23

In [ ]:
dataframe['email'].isna().sum()

30

In [ ]:
dataframe.sort_values(['experience', 'designition_rating', 'skill_count', 'designition_count'], ascending=(False, False, False, False))
dataframe

In [ ]:
dataframe['percentile_rank'] = dataframe.experience.rank(pct=True)
dataframe

level_0  index  ... skill_count percentile_rank
0         61     79  ...         128        1.000000
1         44     55  ...         183        0.990798
2          2      2  ...         117        0.990798
3         68     90  ...         182        0.975460
4         26     34  ...         108        0.975460
..       ...    ...  ...         ...             ...
158       87    116  ...         241        0.042945
159      133    186  ...         196        0.015337
160       62     80  ...          48        0.015337
161        6      8  ...          15        0.015337
162      152    214  ...         105        0.015337

[163 rows x 15 columns]

In [ ]:
dataframe['percentile_rank']

In [ ]:
dataframe['percentile_rank'] = dataframe['percentile_rank']*5
dataframe['percentile_rank'] = dataframe['percentile_rank'].apply(numpy.ceil)

In [ ]:
dataframe

level_0  index  ... skill_count percentile_rank
0         61     79  ...         128             5.0
1         44     55  ...         183             5.0
2          2      2  ...         117             5.0
3         68     90  ...         182             5.0
4         26     34  ...         108             5.0
..       ...    ...  ...         ...             ...
158       87    116  ...         241             1.0
159      133    186  ...         196             1.0
160       62     80  ...          48             1.0
161        6      8  ...          15             1.0
162      152    214  ...         105             1.0

[163 rows x 15 columns]

In [ ]:
dataset = dataframe[['experience', 'designition_rating', 'designition_count', 'skill_count', 'percentile_rank']]

In [ ]:
X = dataset.drop('percentile_rank', axis=1)
y = dataset['percentile_rank']

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train.shape, y_train.shape

((130, 4), (130,))

In [ ]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression().fit(X_train, y_train)
predict = lr.predict(X_test)

Feature Importance

In [ ]:
importance = lr.coef_
for i,v in enumerate(importance):
  print('Feature %0d, Score %.5f' % (i,v))

Feature 0, Score 0.26974
Feature 1, Score 0.00280
Feature 2, Score -0.02863
Feature 3, Score -0.00106


In [ ]:
lr.score(X, y)

0.8786072022479279

In [ ]:
import pickle
with open('linear_regressor.pkl','wb') as f:
  pickle.dump(lr, f)

In [ ]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(predict, y_test)

0.43956186383826

In [ ]:
ceil_value = numpy.ceil(predict)
ceil_value = numpy.where(ceil_value > 5, 5, ceil_value)
ceil_value = numpy.where(ceil_value < 1, 1, ceil_value)

0.7575757575757576

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test, ceil_value))

              precision    recall  f1-score   support

         1.0       1.00      0.25      0.40         8
         2.0       0.25      0.50      0.33         4
         3.0       0.78      1.00      0.88         7
         4.0       1.00      1.00      1.00         4
         5.0       1.00      1.00      1.00        10

    accuracy                           0.76        33
   macro avg       0.81      0.75      0.72        33
weighted avg       0.86      0.76      0.75        33



In [ ]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, ceil_value))

[[ 2  6  0  0  0]
 [ 0  2  2  0  0]
 [ 0  0  7  0  0]
 [ 0  0  0  4  0]
 [ 0  0  0  0 10]]
